### ISSUE TITLE
Webhook callback failed

### ISSUE THREAD

**Issue by wecxxx** [line/line-bot-sdk-python#145]
## The main issue

I am deploying the examplar bot from readme.rst as an experimental run to to the cloud, but the callback function keeps jump to except and returns invalid reply token error `The webhook returned an invalid HTTP status code. (The expected status code is 200.)`

## Code wise

```py
import sys

from flask import Flask, request, abort

from linebot import (
    LineBotApi, WebhookHandler
)
from linebot.exceptions import (
    InvalidSignatureError
)
from linebot.models import (
    MessageEvent, TextMessage, TextSendMessage,
)

app = Flask(__name__)

line_bot_api = LineBotApi('Obe1lI7DmlcB/Q3fBR+CmzmlwaTGR0Uubwx9maohNFbA6O2TN1BrbHbkSeKWV3MHRM12TCNFV958z3Em/Muxe/XuIyEN+L0iph1XRt5X6/6kJrCWpnd4nC4pKk9kkq0kn5HjY5s01dxqQ2993LOQBQdB04t89/1O/w1cDnyilFU=')
handler = WebhookHandler('f8377fb5e1f26314ae2162fe6f2997c5')


@app.route("/callback", methods=['GET', 'POST'])
def callback():
    # get X-Line-Signature header value
    signature = request.headers['X-Line-Signature']

    # get request body as text
    body = request.get_data(as_text=True)
    app.logger.info("Request body: " + body)

    # handle webhook body
    try:
        handler.handle(body, signature)
    except InvalidSignatureError:
        abort(400)

    return 'OK'


@handler.add(MessageEvent, message=TextMessage)
def handle_message(event):
    print("success")
    line_bot_api.reply_message(
        event.reply_token,
        TextSendMessage(text=event.message.text))


if __name__ == "__main__":
    app.run()
```
```
Exception on /callback [POST]
Traceback (most recent call last):
  File "/home/myuser/.virtualenvs/myproject/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/myuser/.virtualenvs/myproject/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/myuserr/.virtualenvs/myproject/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/Pymauer/.virtualenvs/myproject/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/myuser/.virtualenvs/myproject/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/myuser/mysite/flask_app.py", line 32, in callback
    handler.handle(body, signature)
  File "/home/myuser/.virtualenvs/myproject/local/lib/python2.7/site-packages/linebot/webhook.py", line 230, in handle
    func(event)
  File "/home/myuserr/mysite/flask_app.py", line 44, in handle_message
    TextSendMessage(text=event.message.text))
  File "/home/myuser/.virtualenvs/myproject/local/lib/python2.7/site-packages/linebot/api.py", line 95, in reply_message
    '/v2/bot/message/reply', data=json.dumps(data), timeout=timeout
  File "/home/myuser/.virtualenvs/myproject/local/lib/python2.7/site-packages/linebot/api.py", line 561, in _post
    self.__check_error(response)
  File "/home/myuser/.virtualenvs/myproject/local/lib/python2.7/site-packages/linebot/api.py", line 584, in __check_error
    raise LineBotApiError(response.status_code, error)
LineBotApiError: LineBotApiError: status_code=400, error_response={"details": [], "message": "Invalid reply token"}
```

I am new to python, and just starting learn virtualenv, All help and solutions are appreciated, thanks

**Comment by zarszz** [comment]
how you solve this problem ?

**Comment by AwesomePeople** [comment]
I don't know why, but It take a long time to response to user so timeout hapended. That's why we got "Invalid reply token" message.

**Comment by laymonage** [comment]
Try deleting the MessageEvent handler and the verification will work. It's because your bot tries to reply to a dummy message sent in the verification process, and it cannot do so since the token is invalid (dummy). You can either ignore the verification (the bot will still work when it catches a valid MessageEvent), or you can check for the token and see if it matches the dummy token (iirc it's `0xdeadbeefdeadbeef` or something) and return `'OK'` if so. See #37 for more details.

Also, you shouldn't post your channel access token and channel secret in public (other people will be able to control your bot).

**Comment by ayushi011** [comment]
Hi @wecxxx 

Did you able to solve this? I am facing the same issue.
Issue: [https://github.com/ayushi011/line-api/issues/2](url)
