### ISSUE TITLE
Sending Images using reply_message function

### ISSUE THREAD

**Issue by Masa-Yume** [line/line-bot-sdk-python#26]
Hello,

How do you reply with an text message and image message. I have tried using the ImageSendMessage class but i keep getting the same error. Just as a test i sent the url of a random 250x250 jpeg i found on the internet and that did not work.

Here is the traceback

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./main.py", line 76, in callback
    preview_image_url=eikoImageResponce
  File "/usr/local/lib/python3.5/dist-packages/linebot/api.py", line 94, in reply_message
    '/v2/bot/message/reply', data=json.dumps(data), timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/linebot/api.py", line 230, in _post
    self.__check_error(response)
  File "/usr/local/lib/python3.5/dist-packages/linebot/api.py", line 239, in __check_error
    raise LineBotApiError(response.status_code, error)
linebot.exceptions.LineBotApiError: <LineBotApiError [The request body has 2 error(s)]>

It says i have two errors in the request body, but I don't really know what they are. In the API reference (https://devdocs.line.me/en/#common-specifications) they show an error message with the summary I am receiving above, with the details included. Is there a way to display the details of the error?

**Comment by Masa-Yume** [comment]
The random 250x250 jpeg I found is http://res.cloudinary.com/demo/image/upload/w_250,h_250,c_fill,f_auto/seagull.jpg

**Comment by Masa-Yume** [comment]
The reason this error kept occuring was because the image i was trying to send was not a valid https url.
