### ISSUE TITLE
Support Rich menu aliases Rich menu switch action apis

### ISSUE THREAD

**Issue by tkgauri** [line/line-bot-sdk-python#331]
News: https://developers.line.biz/en/news/2021/06/21/switch-between-multiple-rich-menus/

**Comment by geo3huruf** [comment]
Traceback (most recent call last):
  File "/app/main.py", line 1241, in handle_text_message
    target = ast.literal_eval(event.message.mention)
  File "/app/.heroku/python/lib/python3.9/ast.py", line 105, in literal_eval
    return _convert(node_or_string)
  File "/app/.heroku/python/lib/python3.9/ast.py", line 104, in _convert
    return _convert_signed_num(node)
  File "/app/.heroku/python/lib/python3.9/ast.py", line 78, in _convert_signed_num
    return _convert_num(node)
  File "/app/.heroku/python/lib/python3.9/ast.py", line 69, in _convert_num
    _raise_malformed_node(node)
  File "/app/.heroku/python/lib/python3.9/ast.py", line 66, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: {"mentionees": [{"index": 5, "length": 14}]}

error metion , plies excample
